# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/lrn_val_invst',
                'doc_host': 'https://pankaj-kvhld.github.io',
                'git_url': 'https://github.com/pankaj-kvhld/lrn_val_invst',
                'lib_path': 'lrn_val_invst'},
  'syms': {'lrn_val_invst.core': {'lrn_val_invst.core.foo': ('core.html#foo', 'lrn_val_invst/core.py')}}}
